# GolangCI-Lint Configuration for Memory Bank

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_test\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
    enable:
      - atomic
      - bools
      - buildtag
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    disable:
      - fieldalignment

  golint:
    min-confidence: 0.8

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/joern1811/memory-bank

  gocyclo:
    min-complexity: 10

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  funlen:
    lines: 100
    statements: 50

  godot:
    check-all: false

  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK

  gofumpt:
    extra-rules: true

  goheader:
    values:
      const:
        COMPANY: Memory Bank
      regexp:
        AUTHOR: .*
    template: |-
      Copyright (c) {{ YEAR }} {{ COMPANY }}
      SPDX-License-Identifier: MIT

  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return

  gomodguard:
    allowed:
      modules:
        - github.com/sirupsen/logrus
        - github.com/spf13/cobra
        - github.com/spf13/viper
        - github.com/mattn/go-sqlite3
        - github.com/stretchr/testify
        - github.com/mark3labs/mcp-go

  gosec:
    excludes:
      - G404 # Weak random number generator (math/rand instead of crypto/rand)

  lll:
    line-length: 120

  misspell:
    locale: US

  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

  rowserrcheck:
    packages:
      - github.com/jmoiron/sqlx

  testpackage:
    skip-regexp: (export|internal)_test\.go

  unparam:
    check-exported: false

  unused:
    check-exported: false

  whitespace:
    multi-if: false
    multi-func: false

  wsl:
    strict-append: true
    allow-assign-and-call: true
    allow-multiline-assign: true
    allow-cuddle-declarations: false
    allow-trailing-comment: false
    force-case-trailing-whitespace: 0
    force-err-cuddling: false
    allow-separated-leading-comment: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
        - staticcheck
    
    - path: test_utils\.go
      linters:
        - unused
        - staticcheck

  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
      severity: info
    - linters:
        - gocritic
      severity: warning