version: 2

project_name: memory-bank

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: memory-bank
    main: ./cmd/memory-bank
    binary: memory-bank
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/joern1811/memory-bank/internal/infra/cli.version={{.Version}}
      - -X github.com/joern1811/memory-bank/internal/infra/cli.commit={{.Commit}}
      - -X github.com/joern1811/memory-bank/internal/infra/cli.date={{.Date}}

archives:
  - id: memory-bank
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^build:"
      - "^ci:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  name_template: "{{.ProjectName}} v{{.Version}}"
  footer: |
    ## Installation
    
    ### Homebrew (macOS/Linux)
    ```bash
    brew install --cask joern1811/tap/memory-bank
    ```
    
    ### Manual Installation
    Download the appropriate binary for your platform from the assets above.
    
    ## Usage
    
    ### MCP Server Mode (for Claude Code)
    ```bash
    ./memory-bank
    ```
    
    ### CLI Mode
    ```bash
    ./memory-bank --help
    ```

homebrew_casks:
  - name: memory-bank
    binary: memory-bank
    repository:
      owner: joern1811
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/joern1811/memory-bank"
    description: "Semantic memory management system for Claude Code using hexagonal architecture"
    license: "MIT"
    commit_author:
      name: "Jörn Dombrowski"
      email: "joern.dombrowski@gmail.com"
    skip_upload: auto
    caveats: |
      Memory Bank works out-of-the-box with mock providers, but for enhanced performance, 
      consider installing these optional services:

      For local embedding generation:
        brew install ollama
        ollama pull nomic-embed-text

      For vector search performance:
        # Option 1: Python package
        pip install chromadb

        # Option 2: uvx (no installation needed)
        uvx --from 'chromadb[server]' chroma run --host localhost --port 8000

        # Option 3: Docker
        docker run -p 8000:8000 chromadb/chroma

      Start Memory Bank MCP server:
        memory-bank
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memory-bank"]
          system "#{staged_path}/memory-bank completion bash > #{HOMEBREW_PREFIX}/etc/bash_completion.d/memory-bank"
          system "#{staged_path}/memory-bank completion zsh > #{HOMEBREW_PREFIX}/share/zsh/site-functions/_memory-bank"  
          system "#{staged_path}/memory-bank completion fish > #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/memory-bank.fish"